# Because everyone would get the joke if it were 42.
# In a production system, make this a fairly big number; you want to take a
#   substantial fraction of a second while producing a hash. This will make
#   things hard for blackhats.
hash_iterations: 37

# The guidance at https://www.owasp.org/index.php/Hashing_Java suggests that
#   a key length of 256 bytes is safe.
hash_key_length: 256

# The guidance at https://www.owasp.org/index.php/Hashing_Java suggests that
#   some systems won't hava the ...SHA512 algorithm; if so, try the SHA1
#   version: PBKDF2WithHmacSHA1. The SHA1 algorithm is safe when it is paired
#   with PBKDF2. Apparently.
hash_algorithm: PBKDF2WithHmacSHA512

# Database settings.
database:

  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password: sa

  # the JDBC URL
  url: jdbc:h2:./config/h2

swagger:
  resourcePackage: com.yoyodyne.tracker.resource

# HTTP server settings
server:
  type: simple
  applicationContextPath: /tracker
  connector:
    type: http
    port: 8080

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    com.yoyodyne.trackeer: DEBUG

    # Redirects SQL logs to a separate file
    org.hibernate.SQL:
      level: DEBUG

# Logback's Time Based Rolling Policy - archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}.log.gz
# Logback's Size and Time Based Rolling Policy -  archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
# Logback's Fixed Window Rolling Policy -  archivedLogFilenamePattern: /tmp/application-%i.log.gz

  appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: ./logs/tracker.log
      archivedLogFilenamePattern: ./logs/tracker-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB

## the key needs to match the suffix of the renderer
#viewRendererConfiguration:
#    .ftl:
#        strict_syntax: yes
#        whitespace_stripping: yes

#metrics:
#  reporters:
#    - type: graphite
#      host: localhost
#      port: 2003
#      prefix: example
#      frequency: 1m
